services:
  app:
    build:
      context: ../repo
      dockerfile: Dockerfile
    container_name: abw-app
    restart: unless-stopped
    volumes:
      - ./data/db_config.local.json:/app/db_config.local.json:ro
    networks:
      - web

networks:
  web:
    external: true
